document: feedback-pipeline-workload
version: 1
data:
  name: Compression
  description: Tools for file compression
  maintainer: sst_cs_plumbers
  packages:
    - bzip2
    - gzip
    - lz4
    - lzop
    - unzip
    - zip
    - zstd
    - zziplib-utils
  labels:
    - eln
    - c10s
